### ISSUE TITLE
Data????

### ISSUE THREAD

**Issue by YangParky** [YBZh/Point-DAE#1]
When you release your data? 
![1704382844281](https://github.com/YBZh/Point-DAE/assets/38532963/0eee37a8-a380-441a-9e76-5dcaa865a405)

**Comment by YBZh** [comment]
Thanks for your interest. The ShapeNet data for Point-DAE is totally the same as that of the Point-MAE and Point-Bert [shapenet](https://github.com/lulutang0608/Point-BERT/blob/49e2c7407d351ce8fe65764bbddd5d9c0e0a4c52/DATASET.md). In other words, only the point position is used.   If you need the normal information, please refer to: [normal](https://github.com/YBZh/MaskSurf/issues/4)
