### ISSUE TITLE
Some datasets are unclear?

### ISSUE THREAD

**Issue by SebastianLZJ** [YBZh/Point-DAE#4]
Hello, I am very interested in your work. When I was reproducing your code, I found that I was missing the dataset, and many of the files in the paths were not explained. 
For example, the folder shapenet_pc_pointbert_estimated_normal_curve mentioned in PC_PATH: data/ShapeNet55-34/shapenet_pc_pointbert_estimated_normal_curve does not exist. In my shapenet55-34, there is only a folder named shapenet_pc_masksurf_with_normal that I created myself, which contains the shapenet55-34 dataset. 
When I ran the command CUDA_VISIBLE_DEVICES=0 python main.py --config cfgs/pretrain_PointCAE_affine_r3_dropout_local_4xlonger.yaml --exp_name output, I encountered the following error: FileNotFoundError: [Errno 2] No such file or directory: 'data/ShapeNet55-34/shapenet_pc_pointbert_estimated_normal_curve/02691156-2ec4d9949f80154b7a571401e6605fc2.npy'. 
Looking forward to your response with great appreciation.

**Comment by YBZh** [comment]
Sorry for the confusion. You can replace the "shapenet_pc_pointbert_estimated_normal_curve" file with your "shapenet_pc_masksurf_with_normal". And it is also ok to replace the "shapenet_pc_pointbert_estimated_normal_curve" file with the "shapenet_pc" file in Point-Bert (see [data prepare in Point-Bert](https://github.com/Julie-tang00/Point-BERT/blob/master/DATASET.md))

The difference among the three files mentioned above lies in the various methods they use to compute normal and curve representation. However, in Point-DAE, we only utilized xyz information and did not use normal and curve. Therefore, any of the files mentioned above can be used.
